spring:
  application:
    name: book-network-api
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB

#springdoc-openapi
springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/

logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR